### ISSUE TITLE
pushRtmpAddres与pullRtmpAddress 怎么设置？

### ISSUE THREAD

**Issue by gexiaopeng** [yangjiechina/JGB28181#4]
请问config.pullRtmpAddress与config.pushRtmpAddress 怎么样设置？具体表示什么意思？谢谢！

**Comment by yangjiechina** [comment]
你的rtmp服务器，推流地址和拉流地址。

**Comment by gexiaopeng** [comment]
请问有rtmp服务器测试demo吗？

**Comment by yangjiechina** [comment]
windows:https://github.com/illuspas/nginx-rtmp-win32
linux上自行编译nginx-rtmp/srs

**Comment by gexiaopeng** [comment]
谢谢！

**Comment by gexiaopeng** [comment]
这两个参数配置相同地址吗？

**Comment by yangjiechina** [comment]
可以。结合你的实际部署环境。

**Comment by gexiaopeng** [comment]
现在我的电脑运行了两个程序，一个是你的JGB28181(摄像头可以注册)，另外一个是GB28181ToRtmp,那么这两个地址都配置为：rtmp://127.0.0.1:1935/hls/ 吗？

**Comment by yangjiechina** [comment]
只要你的rtmp 应用有叫 hls 就可以。

**Comment by gexiaopeng** [comment]
GB28181ToRtmp默认配置，有live与hls两个应用

**Comment by yangjiechina** [comment]
那应该没问题

**Comment by gexiaopeng** [comment]
好像不能播放，我的qq:7539472 方便联系吗？谢谢！

**Comment by gexiaopeng** [comment]
用你的JGB28181程序，结合 VLC客户端，可以直播摄像头吗？

**Comment by yangjiechina** [comment]
创建一个了QQ群：689592999
